version: "3.3"

services:
  api-codeforces:
    build: ./api-codeforces
    image: mukanjy0/api-codeforces
    ports:
      - 8000:8000
  api-atcoder:
    build: ./api-atcoder
    image: mukanjy0/api-atcoder
    ports:
      - 8001:8000
  api-topcoder:
    build: ./api-topcoder
    image: mukanjy0/api-topcoder
    ports:
      - 8002:8000
  frontend:
    build: ./vite-project
    ports:
      - 8080:3000
    environment:
      - NODE_ENV=production
