INSERT INTO users (handle, email, firstName, lastName, country, city, rank, rating) VALUES
('tourist', 'tourist@protonmail.com', 'Gennady', 'Korotkevich', 'Belarus', 'Gomel', 'legendary grandmaster', 3979),
('jiangly', 'jiangly@protonmail.com', 'Lingyu', 'Jiang', 'China', 'Chongqing', 'legendary grandmaster', 3859),
('Radewoosh', 'Radewoosh@protonmail.com', 'Mateusz', 'Radecki', 'Poland', 'Warsaw', 'legendary grandmaster', 3759),
('ecnerwala', 'ecnerwala@protonmail.com', 'Andrew', 'He', 'United States', 'Cupertino', 'legendary grandmaster', 3668),
('jqdai0815', 'jqdai0815@protonmail.com', 'Jiangqi', 'Dai', 'Samoa', 'Falefa', 'legendary grandmaster', 3681),
('maroonrk', 'maroonrk@protonmail.com', 'Riku', 'Kawasaki', 'Japan', 'Tokyo', 'legendary grandmaster', 3650),
('gamegame', 'gamegame@protonmail.com', 'Harris', 'Leung', 'Hong Kong', '', 'legendary grandmaster', 3402),
('Um_nik', 'Um_nik@protonmail.com', 'Aleksei', 'Daniliuk', 'United Kingdom', 'London', 'legendary grandmaster', 3663),
('ksun48', 'ksun48@protonmail.com', 'Kevin', 'Sun', 'Canada', '', 'legendary grandmaster', 3654),
('maspy', 'maspy@protonmail.com', '', '', 'Japan', 'Tokyo', 'legendary grandmaster', 3317),
('Rewinding', 'Rewinding@protonmail.com', 'Mingyang', 'Deng', 'China', 'Beijing', 'legendary grandmaster', 3659),
('Petr', 'Petr@protonmail.com', 'Petr', 'Mitrichev', 'Switzerland', 'Zurich', 'legendary grandmaster', 3597),
('conqueror_of_tourist', 'conqueror_of_tourist@protonmail.com', 'Dilhan', 'Salgado', 'United States', '', 'legendary grandmaster', 3260),
('BurnedChicken', 'BurnedChicken@protonmail.com', 'Chung-Chun', 'Huang', 'Taiwan', '', 'legendary grandmaster', 3255),
('hos.lyric', 'hos.lyric@protonmail.com', 'Yui', 'Hosaka', 'Japan', 'Tokyo', 'legendary grandmaster', 3338),
('potato167', 'potato167@protonmail.com', '', '', 'Japan', '', 'legendary grandmaster', 3196),
('Ormlis', 'Ormlis@protonmail.com', 'Fedor', 'Romashov', 'Russia', 'Barnaul', 'legendary grandmaster', 3410),
('Kevin114514', 'Kevin114514@protonmail.com', 'Qiwen', 'Xu', 'China', 'Zhijiang', 'legendary grandmaster', 3143),
('noimi', 'noimi@protonmail.com', 'Kentaro', 'Matsushita', 'Japan', 'Tokyo', 'legendary grandmaster', 3353),
('QAQAutoMaton', 'QAQAutoMaton@protonmail.com', 'Kai', 'Luo', 'China', 'Changsha', 'legendary grandmaster', 3428);
